### ISSUE TITLE
Question regarding blenderproc

### ISSUE THREAD

**Issue by HannahHaensen** [gyhandy/Neural-Sim-NeRF#1]
is there a specific reason why you used the old version of blenderproc with the yaml files?

**Comment by gyhandy** [comment]
No, the new version also works.

**Comment by HannahHaensen** [comment]
alright thank you. can you maybe provide the full code, files like `data_generation-Blender.py` are missing

**Comment by gyhandy** [comment]
Yes, we are preparing more detailed instructions, will update as soon as possible, thanks!

**Comment by gyhandy** [comment]
We have added instructions and code to generate training data through BlenderProc.
