### ISSUE TITLE
Question about experiment in YCB Video dataset

### ISSUE THREAD

**Issue by yokies** [gyhandy/Neural-Sim-NeRF#3]
I wonder why there is a different result between 0-shot, 10-shot and 25-shot when use synthetic data(Table2 (a) rows 2 and 3). I think the differnt setting of _YCBVtrain_ has no influence over the synthetic data generation and training progress of detector. Or does the _(pre)_ means that detection model is pre-trained on each few-shot _YCBVtrain_?

**Comment by gyhandy** [comment]
Thanks for your question. Yes, (_pre_) means we use different few-shot images to train the detector before we add the optimization.
